version: '3.4'

services:
  khachhang.api:
    image: ${DOCKER_REGISTRY}khachhangapi
    build:
      context: .
      dockerfile: khachhang.api\Dockerfile
    ports:
      - "8001:80"

  quanlidochoi:
    image: ${DOCKER_REGISTRY}quanlidochoi
    build:
      context: .
      dockerfile: QuanLiDoChoi\Dockerfile
    environment:
      - KhachHangUrl=http://khachhang.api
    ports:
      - "8000:80"
    restart: on-failure
    depends_on:
      - khachhang.api

