version: '3.4'

services:
  khachhang.api:
    image: ${DOCKER_REGISTRY}khachhangapi
    build:
      context: .
      dockerfile: khachhang.api\Dockerfile
    environment:
      - ConnectionString=Server=sql.data;Initial Catalog=QL_TaiKhoan;User Id=sa;Password=Password1
    ports:
      - "8001:80"
    restart: on-failure
    depends_on:
      - sql.data

  quanlidochoi:
    image: ${DOCKER_REGISTRY}quanlidochoi
    build:
      context: .
      dockerfile: QuanLiDoChoi\Dockerfile
    environment:
      - KhachHangUrl=http://khachhang.api
    ports:
      - "8000:80"
    restart: on-failure
    depends_on:
      - khachhang.api


  sql.data:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Password1
      - ACCEPT_EULA=Y
